SELECT sk_symbol,COUNT(*) FROM candle GROUP BY sk_symbol;
/*TRUNCATE TABLE candle;*/

SELECT * FROM candle WHERE open_datetime BETWEEN '2020-02-05' AND '2020-03-20' AND sk_symbol=2 ORDER BY open_datetime
;

SELECT CODE,OPEN_DATETIME, CLOSE FROM SYMBOL sym INNER JOIN CANDLE can ON sym.SK_SYMBOL=can.SK_SYMBOL 
    WHERE sym.CODE='CW8' AND can.TIMEFRAME=1440 ;
    
  SELECT ind.NAME,ind.LABEL,ind.CODE FROM dataset dts
  INNER JOIN ds_content dsc ON dts.SK_DATASET=dsc.SK_DATASET
  INNER JOIN symbol sym ON dsc.SK_SYMBOL=sym.SK_SYMBOL
  INNER JOIN indicator ind ON dsc.SK_INDICATOR=ind.SK_INDICATOR
  WHERE dts.NAME='DCA_CLOSE_1D_V1' AND sym.CODE='CW8';
  
  INSERT INTO ds_content (SK_DATASET,SK_SYMBOL,SK_INDICATOR) VALUES (1,2,31);
  
  SELECT * FROM candle WHERE sk_symbol=2 AND close IS NULL;
  
  DELETE FROM candle WHERE sk_symbol=2 AND close IS NULL;

  --UPDATE candle SET 
  OPEN=ROUND(OPEN,2),
    high=ROUND(high,2),
      low=ROUND(low,2),
  close=ROUND(close,2),
    adj_close=ROUND(adj_close,2);
  
  SELECT ind.* FROM  dataset dts
  INNER JOIN ds_content dsc ON dts.SK_DATASET=dsc.SK_DATASET
  INNER JOIN symbol sym ON dsc.SK_SYMBOL=sym.SK_SYMBOL
  INNER JOIN indicator ind ON dsc.SK_INDICATOR=ind.SK_INDICATOR
  WHERE dts.NAME='DCA_CLOSE_1D_V1' AND sym.CODE='CW8' and ind.type=0;
  
  SELECT dts.SK_DATASET,sym.SK_SYMBOL,lab.SK_INDICATOR AS SK_LABEL,ind.SK_INDICATOR,ind.LABEL FROM dataset dts
  INNER JOIN ds_content dsc ON dts.SK_DATASET=dsc.SK_DATASET
  INNER JOIN symbol sym ON dsc.SK_SYMBOL=sym.SK_SYMBOL
  INNER JOIN indicator ind ON dsc.SK_INDICATOR=ind.SK_INDICATOR and ind.type=1
    INNER JOIN ds_content dsc_lab ON dts.SK_DATASET=dsc_lab.SK_DATASET
	 INNER JOIN indicator lab ON dsc_lab.SK_INDICATOR=lab.SK_INDICATOR AND lab.type=2
  WHERE dts.NAME='DCA_CLOSE_1D_V1' AND sym.CODE='CW8' AND lab.LABEL='lab_perf_21d' 
  AND ind.LABEL IN ('pos_bot_200','pos_sma200') ;
  
  
    CREATE OR REPLACE TABLE `model` (
	`SK_MODEL` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`SK_DATASET` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`SK_SYMBOL` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`SK_LABEL` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`ALGO` VARCHAR(20),
	PRIMARY KEY (`SK_MODEL`) USING BTREE
);

  CREATE OR REPLACE TABLE `ds_filtered` (
	`SK_DS_FILTERED` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`SK_MODEL` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`SK_INDICATOR` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`SK_DS_FILTERED`) USING BTREE
);